### ISSUE TITLE
Support for path aliases with TypeScript

### ISSUE THREAD

**Issue by misterquestions** [g45t345rt/esbuild-style-plugin#4]
Hey!

I'm wondering if it would be possible to get path aliases working when using typescript.

They don't seem to resolve and I get the following issue:

```
X [ERROR] [plugin esbuild-style-plugin] src\ui\views\@styles\main.scss: no such file or directory

    node_modules/sass/sass.dart.js:1254:16:
      1254 │       wrapper = new Error();
           ╵                 ^

    at Object.wrapException (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\sass\sass.dart.js:1254:17)
    at Object._systemErrorToFileSystemException0 (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\sass\sass.dart.js:20745:17)
    at Object._readFile0 (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\sass\sass.dart.js:20723:16)
    at Object.readFile0 (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\sass\sass.dart.js:20711:34)
    at Object.compile (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\sass\sass.dart.js:17420:16)
    at StaticClosure.renderSync (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\sass\sass.dart.js:19943:22)
    at Object.Primitives_applyFunction (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\sass\sass.dart.js:1142:30)
    at Object.Function_apply (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\sass\sass.dart.js:5267:16)
    at _callDartFunctionFast (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\sass\sass.dart.js:22995:16)
    at Object.sass.renderSync (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\sass\sass.dart.js:22973:18)

  This error came from the "onLoad" callback registered here:

    node_modules/esbuild-style-plugin/dist/index.js:195:10:
      195 │     build.onLoad({ filter: /.*/, namespace: LOAD_STYLE_NAMESPACE }, onStyleLoad(options));
          ╵           ~~~~~~

    at setup (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\esbuild-style-plugin\dist\index.js:195:11)
    at handlePlugins (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\esbuild\lib\main.js:845:23)
    at Object.buildOrServe (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\esbuild\lib\main.js:1139:7)
    at C:\Users\miste\Projects\layux\fivem-races\race\node_modules\esbuild\lib\main.js:2080:17
    at new Promise (<anonymous>)
    at Object.build (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\esbuild\lib\main.js:2079:14)
    at build (C:\Users\miste\Projects\layux\fivem-races\race\node_modules\esbuild\lib\main.js:1929:51)
    at Object.<anonymous> (C:\Users\miste\Projects\layux\fivem-races\race\build.js:128:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)

  The plugin "esbuild-style-plugin" was triggered by this import

    src/ui/views/hud.tsx:3:7:
      3 │ import '@styles/main.scss';
        ╵        ~~~~~~~~~~~~~~~~~~~

error Command failed with exit code 1.
```

**Comment by g45t345rt** [comment]
Good idea and certainly possible. 
I might add it this weekend but no promises though.

**Comment by doberkofler** [comment]
I'm having the same problem when trying to migrate from webpack to esbuild.

**Comment by doberkofler** [comment]
My pull request #11 should have resolved this sr.

**Comment by misterquestions** [comment]
Thank you!
