### ISSUE TITLE
Cannot find module when  import css from node_module and use tailwindcss

### ISSUE THREAD

**Issue by nyrf** [g45t345rt/esbuild-style-plugin#8]
Used postcss config file, after refresh some times, it'll got error like that.

```js
module.exports = {
  parser: require('postcss-scss'),
  plugins: [
    require('postcss-import'),
    require('tailwindcss/nesting'),
    require('tailwindcss'),
    require('autoprefixer')
  ]
}
```

appliction.js

```js
import './stylesheets/demo.css'
import 'boxicons/css/boxicons.min.css'
```

demo.css

```css
@import "./tailwind.css";

body {
  color: red;
}

```

tailwind.css

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

```
❯ yarn build --watch
yarn run v1.22.17
$ node esbuild.config.js --watch
Using postcss config file.
✘ [ERROR] [plugin esbuild-style-plugin] Cannot find module '/var/folders/67/w9fqrphn03b5zkz2xxtyd5480000gn/T/2022228-98367-18m6mj4.y2vk.css' from '/Users/nyrf/import_demo/node_modules/boxicons/css'

    ../../node_modules/esbuild-style-plugin/dist/index.js:123:42:
      123 │   const fullPath = import_resolve.default.sync(args.path, { basedir: args.resolveDir });
          ╵                                           ^

    at Function.resolveSync [as sync] (/Users/nyrf/import_demo/node_modules/resolve/lib/sync.js:111:15)
    at onStyleResolve (/Users/nyrf/import_demo/node_modules/esbuild-style-plugin/dist/index.js:123:43)
    at callback (/Users/nyrf/import_demo/node_modules/esbuild/lib/main.js:917:34)
    at handleRequest (/Users/nyrf/import_demo/node_modules/esbuild/lib/main.js:697:36)
    at handleIncomingPacket (/Users/nyrf/import_demo/node_modules/esbuild/lib/main.js:752:7)
    at Socket.readFromStdout (/Users/nyrf/import_demo/node_modules/esbuild/lib/main.js:629:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/esbuild-style-plugin/dist/index.js:188:10:
      188 │     build.onResolve({ filter: styleFilter }, onStyleResolve);
          ╵           ~~~~~~~~~

    at setup (/Users/nyrf/import_demo/node_modules/esbuild-style-plugin/dist/index.js:188:11)
    at async handlePlugins (/Users/nyrf/import_demo/node_modules/esbuild/lib/main.js:881:11)

  The plugin "esbuild-style-plugin" was triggered by this import

    stylePlugin:/Users/nyrf/import_demo/node_modules/boxicons/css/boxicons.min.css:1:7:
      1 │ import "/var/folders/67/w9fqrphn03b5zkz2xxtyd5480000gn/T/2022228-98367-18m6mj4.y2vk.css";
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by g45t345rt** [comment]
I'm not so sure what to do here. Can you create a repo?

**Comment by nyrf** [comment]
Sorry, i've not found it appear again, thanks.

**Comment by mattkauffman23** [comment]
I'm periodically seeing a similar error message.

```
✘ [ERROR] [plugin esbuild-style-plugin] Cannot find module '/var/folders/b9/rlztpdl956j2v98ww77vcvs00000gn/T/202231-30737-1sxo4uz.lhy8.css' from '/Users/mattkauffman/dev/internal/console-ui/node_modules/codemirror/lib'

    node_modules/esbuild-style-plugin/dist/index.js:126:42:
      126 │ ...= import_resolve.default.sync(args.path, { basedi...
          ╵                             ^

    at Function.resolveSync [as sync] (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild-style-plugin/node_modules/resolve/lib/sync.js:111:15)
    at onStyleResolve (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild-style-plugin/dist/index.js:126:43)
    at callback (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:918:34)
    at handleRequest (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:698:36)
    at handleIncomingPacket (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:753:7)
    at Socket.readFromStdout (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:629:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild-style-plugin/dist/index.js:191:10:
      191 │     build.onResolve({ filter: styleFilter }, onStyle...
          ╵           ~~~~~~~~~

    at setup (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild-style-plugin/dist/index.js:191:11)
    at handlePlugins (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:840:23)
    at Object.buildOrServe (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:1134:7)
    at /Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:2076:17
    at new Promise (<anonymous>)
    at Object.build (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:2075:14)
    at Object.build (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:1924:51)
    at file:///Users/mattkauffman/dev/internal/console-ui/build.js:35:30
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)

  The plugin "esbuild-style-plugin" was triggered by this import

    stylePlugin:/Users/mattkauffman/dev/internal/console-ui/node_modules/codemirror/lib/codemirror.css:1:7:
      1 │ import "/var/folders/b9/rlztpdl956j2v98ww77vcvs00000gn...
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Oddly when inspect `codemirror.css` it doesn't have any imports. Also the path of the import that's feeling looks similar to the one nyrf reported. Are those temporary folders created during builds or something?

Building again generally resolves the issue.
