### ISSUE TITLE
Occasional missing import while building

### ISSUE THREAD

**Issue by mattkauffman23** [g45t345rt/esbuild-style-plugin#9]
esbuild-style-plugin crashes periodically when building my project. Happen during ~5% of builds. The project uses `less` and `styledComponents`. The crash always occurs while processing the file in the stack below. When I inspect that css file it doesn't have any imports, so not sure how to debug further.

```
✘ [ERROR] [plugin esbuild-style-plugin] Cannot find module '/var/folders/b9/rlztpdl956j2v98ww77vcvs00000gn/T/202238-71337-12i2h5a.ajbj.css' from '/Users/mattkauffman/dev/internal/console-ui/node_modules/codemirror/theme'

    node_modules/esbuild-style-plugin/dist/index.js:126:42:
      126 │ ...= import_resolve.default.sync(args.path, { basedi...
          ╵                             ^

    at Function.resolveSync [as sync] (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild-style-plugin/node_modules/resolve/lib/sync.js:111:15)
    at onStyleResolve (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild-style-plugin/dist/index.js:126:43)
    at callback (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:918:34)
    at handleRequest (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:698:36)
    at handleIncomingPacket (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:753:7)
    at Socket.readFromStdout (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:629:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild-style-plugin/dist/index.js:191:10:
      191 │     build.onResolve({ filter: styleFilter }, onStyle...
          ╵           ~~~~~~~~~

    at setup (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild-style-plugin/dist/index.js:191:11)
    at handlePlugins (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:840:23)
    at Object.buildOrServe (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:1134:7)
    at /Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:2090:55
    at new Promise (<anonymous>)
    at Object.serve (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:2090:14)
    at Object.serve (/Users/mattkauffman/dev/internal/console-ui/node_modules/esbuild/lib/main.js:1925:70)
    at file:///Users/mattkauffman/dev/internal/console-ui/.esbuild/serve.js:74:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

  The plugin "esbuild-style-plugin" was triggered by this import

    stylePlugin:/Users/mattkauffman/dev/internal/console-ui/node_modules/codemirror/theme/material-ocean.css:1:7:
      1 │ import "/var/folders/b9/rlztpdl956j2v98ww77vcvs00000gn...
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by g45t345rt** [comment]
Yep I got it myself a few days back. I will try to find time next week to fix this.
In the meantime you can downgrade to `1.3.1`

**Comment by nyrf** [comment]
Any update?
